// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package handle_graphql

import (
	"time"
)

type BoardList struct {
	Board string `json:"board"`
	List  string `json:"list"`
}

type Task struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	CreatedDate *time.Time `json:"createdDate"`
	URL         *string    `json:"url"`
}
