// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package handle_graphql

import (
	"time"
)

type BoardList struct {
	Board string `json:"board"`
	List  string `json:"list"`
}

type BoardListInput struct {
	Board string `json:"board"`
	List  string `json:"list"`
}

type GenerateResult struct {
	Message *string `json:"message"`
	Ok      bool    `json:"ok"`
}

type MonthlyGoal struct {
	Title       string        `json:"title"`
	WeeklyGoals []*WeeklyGoal `json:"weeklyGoals"`
}

type Task struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	CreatedDate *time.Time `json:"createdDate"`
	URL         *string    `json:"url"`
	Due         *time.Time `json:"due"`
	List        *BoardList `json:"list"`
	Period      *string    `json:"period"`
}

type WeeklyGoal struct {
	Title string  `json:"title"`
	Tasks []*Task `json:"tasks"`
	Year  *int    `json:"year"`
	Month *int    `json:"month"`
	Week  *int    `json:"week"`
}
