# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/golang:1.12-stretch

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    # working_directory: /go/src/github.com/clarsen/go-trello-workflow

    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}

      - run:
          name: dependencies
          command: |
            go get github.com/gobuffalo/packr/v2/packr2

      - run:
          name: build go binaries
          command: |
            cd server/go
            export GO111MODULE=on  # for packr
            make build

      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

      - persist_to_workspace:
          root: server/go
          paths:
            - bin


  deploy:
    docker:
      - image: circleci/node:10.13-stretch-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - attach_workspace:
          at: workspace

      - run:
          name: grab built binary
          command: |
            cp -rp workspace/bin server/go/.

      - restore_cache:
          keys:
            - node-v1-{{ checksum "server/go/package.json" }}-{{ checksum "web/package.json" }}

      - run:
          name: dependencies
          command: |
            cd server/go
            sudo npm i -g serverless
            npm i

      - run:
          name: deploy
          command: |
            source ./circleci_branch_config.sh
            cd server/go
            serverless deploy --verbose

      - run:
          name: deploy web UI
          command: |
            source ./circleci_branch_config.sh
            cd web
            npm i
            NODE_ENV=production npm run deploy

      - save_cache:
          key: node-v1-{{ checksum "server/go/package.json" }}-{{ checksum "web/package.json" }}
          paths:
            - "server/go/node_modules"
            - "web/node_modules"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          context: org-aws-deploy
          requires:
            - build
          filters:
            branches:
              only:
                - master
