# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/golang:1.12-stretch

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: /go/src/github.com/clarsen/go-trello-workflow

    steps:
      - checkout
      - run:
          name: dependencies
          command: |
            go get -u github.com/gobuffalo/packr/v2/packr2

      - run:
          name: build go binaries
          command: |
            cd server/go
            export GO111MODULE=on  # for packr
            make build


      - persist_to_workspace:
          root: server/go
          paths:
            - bin


  deploy:
    docker:
      - image: circleci/node:10.13-stretch-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - attach_workspace:
          at: workspace

      - run:
          name: grab built binary
          command: |
            cp -rp workspace/bin server/go/.

      - run:
          name: dependencies
          command: |
            sudo npm i -g serverless

      - run:
          name: deploy
          command: |
            source ./circleci_branch_config.sh
            cd server/go
            serverless deploy --verbose

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          context: org-aws-deploy
          requires:
            - build
          filters:
            branches:
              only:
                - master
