service: go-trellow-workflow-app  # NOTE: update this with your service name

plugins:
  - serverless-apigw-binary
  - serverless-domain-manager

custom:
  apigwBinary:
    types:
      - '*/*'
  customDomain:
    domainName: ${file(./secrets.js):getEnvVars.DOMAIN}
    basePath: ''
    stage: ${file(./secrets.js):getEnvVars.NODE_ENV}
    createRoute53Record: true
    # certificateName: '*.app.caselarsen.com'
    certificateArn: arn:aws:acm:us-east-1:671196348897:certificate/9e5f1f08-5690-4ab7-974e-94df4baac5a7

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${file(./secrets.js):getEnvVars.NODE_ENV}
  region: us-east-1
  environment:
    NODE_ENV: ${file(./secrets.js):getEnvVars.NODE_ENV}
  memorySize: 128
  timeout: 10

functions:
  server:
    handler: index.server
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
